// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    partial class EmpresaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ENTITY.Abono", b =>
                {
                    b.Property<string>("Idabono")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorAbono")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Idabono");

                    b.ToTable("Abonos");
                });

            modelBuilder.Entity("ENTITY.Credito", b =>
                {
                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CantidadEmp")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorActivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorCredito")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Identificacion");

                    b.ToTable("Creditos");
                });
#pragma warning restore 612, 618
        }
    }
}
